name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - scipy
  - black
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  - gsw
  - cartopy
  - xgcm
  - pip
  - pip:
    - codecov
    - pytest-cov
