name: test_env
dependencies:
  - python=2.7
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - scipy
  - flake8
  - pip:
    - codecov
    - pytest-cov
    - "--editable=git+https://github.com/xgcm/xgcm.git@master#egg=xgcm"
