name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask
  - numpy
  - pytest
  - scipy
  - black
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  - gsw
  - cartopy
  - pip
  - cf_xarray
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/xgcm/xgcm.git
    - pytest
    - codecov
    - pytest-cov
    - pytest-xdist
